"""create warehouse and serving schemas

Revision ID: 0001_create_schemas
Revises:
Create Date: 2026-08-30

M0 brings the database up to a pair of empty logical schemas. Table DDL is
autogenerated from ``mlbsim_data.models`` in M1.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_create_schemas"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SCHEMAS = ("warehouse", "serving")


def upgrade() -> None:
    for schema in _SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')


def downgrade() -> None:
    for schema in reversed(_SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
